# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name antidiag
#' @title Matrix antidiagonals
#' @description
#' Extract or replace the antidiagonal of a matrix,
#' or construct a antidiagonal matrix.
#' @param x matrix, vector or 1D array, or missing.
#' @param ncol number of columns (optional; when x is not a matrix)
#' @param nrow number of rows (optional; when x is not a matrix)
#' @examples
#' antidiag(diag(3))
#' antidiag(7, 3, 3)
#' antidiag(1:5, 3, 2)
#' @export
antidiag <- function(x = as.numeric( c(1)), nrow = NULL, ncol = NULL) {
    .Call(`_matricks_antidiag`, x, nrow, ncol)
}

